/*
  Don't edit.
  Code generated by type.py.
 */

import 'dart:convert';


class Login {
    String account;
    String pwd;

    Login({
        this.account,
        this.pwd,
    });

    factory Login.fromRawJson(String str) => Login.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory Login.fromJson(Map<String, dynamic> json) => new Login(
        account: json["account"],
        pwd: json["pwd"],
    );

    Map<String, dynamic> toJson() => {
        "account": account,
        "pwd": pwd,
    };
}


class LoginResp {
    int code;
    String msg;

    LoginResp({
        this.code,
        this.msg,
    });

    factory LoginResp.fromRawJson(String str) => LoginResp.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory LoginResp.fromJson(Map<String, dynamic> json) => new LoginResp(
        code: json["code"],
        msg: json["msg"],
    );

    Map<String, dynamic> toJson() => {
        "code": code,
        "msg": msg,
    };
}
