/*
  Don't edit.
  Code generated by type.py.
 */

import 'dart:convert';


//keep
class Test {
    String test;

    Test({
        this.test,
    });

    factory Test.fromRawJson(String str) => Test.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory Test.fromJson(Map<String, dynamic> json) => new Test(
        test: json["test"],
    );

    Map<String, dynamic> toJson() => {
        "test": test,
    };
}
